name: Release

on: workflow_dispatch

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependecies
        run: npm ci
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Release
        run: npm run release
      - name: Commit release
        run: git push --follow-tags origin master
      - name: Create release
        run: https://github.com/limardo/avvocatoluisaparrotta.it/releases/new?tag=v$(cat .version)
  api:
    name: Create Github Release
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Data
        id: data
        run: |
          echo ::set-output name=tag_name::$(cat .version)
          echo ::set-output name=body::$(cat .version)
      - name: Call Github api release
        run: |
          curl --request POST
          --url https://api.github.com/repos/${{ github.repository }}/releases \
              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --header 'content-type: application/json' \
              --data '{
                "tag_name": "v${{ steps.data.outputs.tag_name }}"
              }' \
              --fail
